"""Type stubs for shared_ollama.core.utils module."""

from pathlib import Path

def get_ollama_base_url() -> str: ...
def check_service_health(
    base_url: str | None = ...,
    timeout: int = ...,
) -> tuple[bool, str | None]: ...
def ensure_service_running(
    base_url: str | None = ...,
    raise_on_fail: bool = ...,
) -> bool: ...
def get_project_root() -> Path: ...
def get_client_path() -> Path: ...
def import_client() -> type: ...
def get_default_vlm_model() -> str: ...
def get_default_text_model() -> str: ...
def get_warmup_models() -> list[str]: ...
def get_allowed_models() -> set[str]: ...
def is_model_allowed(model_name: str | None) -> bool: ...
